### PR TITLE
[stdlib] Clean up `b64encode` (2/N)

### PR DESCRIPTION
**Pull request by soraros**

### CODE REVIEW

**Review by JoeLoser — APPROVED** [review]

**Comment by JoeLoser** [comment]
!sync

**Comment by soraros** [comment]
@JoeLoser It seems that this PR was reverted in 174104c. I can fix the code if the team could share the internal failing tests.

**Comment by JoeLoser** [comment]
> @JoeLoser It seems that this PR was reverted in [174104c](https://github.com/modularml/mojo/commit/174104c336e13faaae8a5af0af816f1fa6a9487a). I can fix the code if the team could share the internal failing tests.

Hey @soraros, thanks for the ping.  This was the (indeterminate it seemed) failing test on an m7i machine:

```
FAIL: Mojo Standard Library :: base64/test_base64.mojo (11 of 128)
******************** TEST 'Mojo Standard Library :: base64/test_base64.mojo' FAILED ********************
Exit Code: 1

Command Output (stdout):
--
Unhandled exception caught during execution: At /__w/modular/modular/stdlib/test/base64/test_base64.mojo:29:17: AssertionError: `left == right` comparison failed:
   left: dGhlIHF1aWNrIGJ=============================================
  right: dGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZw==

--
Command Output (stderr):
--
RUN: at line 13: mojo -D ASSERT=all /__w/modular/modular/stdlib/test/base64/test_base64.mojo
+ mojo -D ASSERT=all /__w/modular/modular/stdlib/test/base64/test_base64.mojo
mojo: error: execution exited with a non-zero result: 1
```

Note that it passed in our pre-submit checks (which we also run on m7i), but then later was sporadically failing throughout the day, which is why we reverted to get back to a known stable state to unblock the nightlies.  I haven't triaged it further/looked into the failure, but @Ahajha may have some more info.

**Comment by Ahajha** [comment]
I didn't look into the error much. My best guess is that it's indeterminate, but that seems odd for this kind of test. It's also possible this had some sort of collision with another unrelated change. Perhaps rebasing this PR on main and rerunning CI might give us some insight.

**Pull request closed without merging**
