### PR TITLE
[Docs] Fix minor typos

### PR DESCRIPTION
**Pull request by carun**

### CODE REVIEW

**Comment by Brian-M-J** [comment]
A few fixes you suggested have already been applied in the `nightly` branch:
- The [first fix](https://github.com/modularml/mojo/pull/2694/files#diff-6a17656d764b8e1930354f341cf7f47960b63845c3046edcd8bbf282aaa2f464L239) - in [commit 6890241](https://github.com/modularml/mojo/commit/68902417140ebe0592244dde17abd174eb1d6422#diff-6a17656d764b8e1930354f341cf7f47960b63845c3046edcd8bbf282aaa2f464L234).
- The [last 2 fixes](https://github.com/modularml/mojo/pull/2694/files#diff-c860319581b52a85f8c1f7d9f87938fc5a6245b7d3bf174574b6ddba359c358aL20) - in [commit b6e0d2b](https://github.com/modularml/mojo/commit/b6e0d2be25582590966f4e3aac85aa4214396c6b#diff-6bc7e697e75b0be9a71605272cc8b6fc66812fe92f07cd8eec25881a5c4939adL27).

**Comment by laszlokindrat** [comment]
@carun Thanks for fixing these! Could you please rebase on the latest nightly and change the target branch of the PR?

**Comment by carun** [comment]
@laszlokindrat it looks like majority of the fixes have been taken care of already, which is great. Just a few fixes pending to correct the spellings from UK to International.

**Review by laszlokindrat — APPROVED** [review]
Thank you!

**Comment by laszlokindrat** [comment]
Before I bring this in, could you please make sure CI is green?

**Comment by carun** [comment]
@laszlokindrat I think the DCO is failing due to missing sign-offs in the unrelated commits. My commit is already signed.

**Comment by laszlokindrat** [comment]
!sync

**Pull request closed without merging**
