### PR TITLE
Roundable trait with ndigits param in the round operation

### PR DESCRIPTION
**Pull request by msaelices**
**Note**: Please do not merge until this was merged: https://github.com/modularml/mojo/pull/2558

* Add `Roundable.__round__(ndigits)` method
* Implement the method in all the types that adhere to `Roundable`
* Tests

### CODE REVIEW

**Comment by laszlokindrat** [comment]
Could you please rebase this on the latest nightly? I would love to start reviewing it, it's a great improvement!

**Comment by laszlokindrat** [comment]
@msaelices Could you please rebase this after the next nightly? Lots of adjacent changes have landed in the past three days, but I would really like to bring this in!

**Comment by msaelices** [comment]
> @msaelices Could you please rebase this after the next nightly? Lots of adjacent changes have landed in the past three days, but I would really like to bring this in!

I will create another PR tomorrow. Rebasing this is becoming a nightmare. Now it shows 110 files changes which is NOT the case:

image

**Comment by msaelices** [comment]
Closed in favor of this PR: https://github.com/modularml/mojo/pull/2752

**Pull request closed without merging**
