### PR TITLE
[stdlib] implement `has_single_bit`

### LINKED ISSUE #2682: [stdlib] Implement missing functions in the `bit` module
For example: `bit_ceil`, `bit_floor`, `has_single_bit`, and others. The immediate goal is to achieve (or get pretty close to) parity with [Cpp's `<bit>`](https://en.cppreference.com/w/cpp/header/bit). We shouldn't blindly follow the naming, and we can deviate from or extend some of these APIs slightly if we have a good reason to. Many of these functions might be simple wrappers around intrinsics.

See comment: https://github.com/modularml/mojo/commit/3f9fa057a9587f26e217344e663cc77513c0002a#diff-20568bce7de07632ece5bf3e933c7e2eec19706a949dcae48ddd4299309ddd10R249

### PR DESCRIPTION
**Pull request by jiex-liu**
fix #2682

### CODE REVIEW

**Review by JoeLoser — APPROVED** [review]
Looks good, thank you!

**Comment by JoeLoser** [comment]
!sync

**Comment by soraros** [comment]
- Should this be called `is_power_of_2`? `math` has that already.
- We should replace `_is_power_of_2` with this function.

**Comment by JoeLoser** [comment]
> * Should this be called `is_power_of_2`? `math` has that already.
> * We should replace `_is_power_of_2` with this function.
> * We could write `(val != 0) & (val & (val - 1) == 0))` in both implementations (`Int` also).
> * Why is this preferred over `popcount(val) == 1`?

For (2), I already have a PR up for review internally; I also removed `is_power_of_2` from `math` in that same PR. 

For (3), feel free to use `!=` instead of `>`, I'd welcome a PR on top of this.

**Pull request closed without merging**
