### PR TITLE
[stdlib] Constrain `simd.bool()` to `size == 1`

### PR DESCRIPTION
**Pull request by helehex**
Use explicit `reduce_or()`/`reduce_and()` instead
see https://github.com/modularml/mojo/pull/2412

### CODE REVIEW

**Comment by soraros** [comment]
Actually, I wish they were called `any` and `all`.

**Comment by helehex** [comment]
i was thinking the same thing, but they can be separate to avoid bitwise ambiguity

**Comment by JoeLoser** [comment]
Just a quick update here: this has been approved internally, but I need to go fix up more uses internally this breaks before we can land it.

**Review by JoeLoser — APPROVED** [review]

**Comment by helehex** [comment]
I was about to try adding `any`/`all` functions, but my Internet connection just died, so if anyone wants something todo

**Comment by helehex** [comment]
I thought there was something else that should get done before `any`/`all`, but I can't remember now

**Pull request closed without merging**
