### PR TITLE
[stdlib] use `ref[_]` in Optional.value() return type

### PR DESCRIPTION
**Pull request by lsh**
Since auto-deref is possible with the new `ref[_]` return annotation, this PR wires it up for `Optional.value()`.

### CODE REVIEW

**Review by JoeLoser — APPROVED** [review]
Looks good, do you mind resolving the merge conflicts though @lsh?  Thanks.

**Comment by YichengDWu** [comment]
Can someone merge this?

**Comment by JoeLoser** [comment]
!sync

**Comment by JoeLoser** [comment]
> Can someone merge this?

I'd love to, but there are still merge conflicts, so I can't import this PR to land it.

**Comment by JoeLoser** [comment]
!sync

**Comment by JoeLoser** [comment]
@lsh FYI I fixed the merge conflicts from this morning's release and imported the PR internally just now.

**Pull request closed without merging**
