### PR TITLE
[mojo-stdlib][docs] Update docs and code to use `from <module> import <entity>` instead of `from <module>.<file> import <entity>`

### PR DESCRIPTION
**Pull request by FarhanAliRaza**
It is wip for issue https://github.com/modularml/mojo/issues/2023
Signed-off-by: Farhan Ali Raza <farhanalirazaazeemi@gmail.com>

### CODE REVIEW

**Comment by FarhanAliRaza** [comment]
# TODO: consider making Arc public and import it here
there is this line so should i create a pr. i dont know there is an issue for it

**Review by JoeLoser — COMMENTED** [review]
Generally looks good, thank you for doing this!  Do you mind rebasing with the latest `nightly` branch and resolving the two file conflicts from today's new nightly compiler + library changes?  Once that is done, I'll prioritize getting this in to avoid future conflicts for you.

**Comment by JoeLoser** [comment]
Looks like CI is failing due to formatting.  If your remote to this upstream repo is `upstream`, you can do this to format all the changed files from your branch:

```
git diff upstream/nightly --name-only -- '*.mojo' | xargs mojo format -l 80
```

**Comment by ConnorGray** [comment]
Hi Farhan, thanks for running that formatting change. 

From reading the CI failure above, it looks like your branch may still be using an older version of the Mojo compiler.

Could you confirm that you checked out the latest changes on the `nightly` branch, and the did a `git rebase` of your branch to ensure it is based on the latest `nightly` branch changes?

**Comment by FarhanAliRaza** [comment]
I followed a tutorial from https://www.squash.io/how-to-rebase-local-branch-onto-remote-master-in-git/

Can you tell me the exact command I need to run .
I was checked out to my branch .

git pull --rebase nightly

Then resolved conflicts and pushed

**Comment by ConnorGray** [comment]
Hi Farhan, thanks for trying that. 

I haven't used `git pull --rebase` myself, but from reading about it, it looks reasonable.

However, I noticed that the [list of commits for this PR](https://github.com/modularml/mojo/pull/2039/commits) seems to have grown, and appears to include duplicate copies of the same commits, as well as commits from other authors. Unfortunately I think this may mean some manual and slightly cumbersome cleanup effort is needed.

You might consider trying the following steps, [using an interactive rebase](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#:~:text=With%20the%20interactive%20rebase%20tool) to manually review which commits are included in your PR, and remove any duplicates:

```
# Ensure nightly is up-to-date
$ git checkout nightly
$ git pull

# Check out your branch
$ git checkout update-docs-and-code-to-use-from-module-import-entity

# Begin an interactive rebase
$ git rebase -i nightly
```

The interactive rebase terminal UI will let you edit or drop commits that you did not create or that have accidentally been duplicated.

A word of warning though, you may want to make a backup of your original branch to avoid loosing any commits if you happen to accidentally drop the wrong commits during your first attempt at an interactive rebase.

I hope these instructions are helpful and help resolve the issue—please let me know if you have any further questions. Thanks again for working with us to make this contribution :)

**Comment by FarhanAliRaza** [comment]
I run the rebase command.
There are conflicts .
I resolve those conflicts all 107 commits of them .
It says rebase successfull.
I sync with repo.
New commits are added to repo which appears here but test fails.
I rerun the rebase command.
It starts the rebase process again.
Same cycle repeats.
I am suggesting I can redo the changes and create a new pr from the latest nightly branch .
I have done more work on this rebasing then the actual issue 🥲.
I don't know what I am doing wrong .
I am sorry 😔 for wasting your time.

**Comment by FarhanAliRaza** [comment]
I was using vs code to push the code after rebasing. But after rebase a force push is required if your pull request is published.

Now tests are passing locally now the issue is only formatting.

**Comment by ConnorGray** [comment]
Amazing, thank you Farhan for working through those git issues🙂 I know that's nobodies favorite kind of work.

Regarding the formatting, it looks like you're running into a known issue (fixed earlier this morning in https://github.com/modularml/mojo/pull/2158): you will need to format your code locally with `mojo format -l 80`, as `mojo format` on its own defaults to formatting to 88 columns. The CI checks use 80 columns, hence the mismatch and failing check.

Thank you for your work so far, early contributors like you are driving a lot of improvements—so thanks again for bearing with us as we sort out these early issues :)

**Comment by ConnorGray** [comment]
Amazing, thanks for fixing the formatting Farhan.

Unfortunately, the last remaining issue is that each commit needs to include the `Signed-off-by` section.

For this particular PR, you can add automatically with this command:

```
git rebase HEAD~3 --signoff
git push --force
```

Which will add `Signed-off-by: ...` to the 3 commits in this PR.

Once that's added, we should be good to merge🙂

Thanks again Farhan! I'll be awesome to get this change in :)

**Comment by JoeLoser** [comment]
Hey @FarhanAliRaza, I think something went wrong during your rebase.  The latest set of file diffs doesn't look quite right. 
 Do you mind taking a look?

**Comment by FarhanAliRaza** [comment]
https://github.com/modularml/mojo/pull/2219
I opened a new PR here. in this PR issues are increasing instead of decreasing. 
I redid the work there from scratch.

**Pull request closed without merging**
