### PR TITLE
[mojo-stdlib] implement all bitwise operators for `object`

### LINKED ISSUE #2320: [Feature Request][stdlib] Request for implementation for all bitwise operation for object
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Requesting for implementing all bitwise operation in object. This include implementing a method that handles type casting for integral type and also applying functors to the dunder methods. I already have an implementaion for this and will wait for #2247 to be merged before I start a new pr.

### What is your motivation for this change?

Right now bitwise operation such as and/or/xor still only support bool type(xor has not been implemented yet).

### Any other details?

_No response_

### PR DESCRIPTION
**Pull request by jiex-liu**
Fix #2320

### CODE REVIEW

**Comment by JoeLoser** [comment]
Thanks for the contribution! 🎉 

I'm out of office for the first part of this week (Monday - Wednesday), so I think @ConnorGray will try to take a look at this, otherwise I will take a look when I'm back.

**Comment by LJ-9801** [comment]
@JoeLoser Hi sorry for the late respond. Have been busy for the past few days. No problem! I will update this branch once it is reviewed and approved.

**Comment by LJ-9801** [comment]
@JoeLoser I believe this pr is ready for review. Thanks!

**Review by JoeLoser — APPROVED** [review]
Looks great, thank you for the contribution!  Sorry for the long delay in getting this through on my end.  I've imported it now and it should land soon.

**Comment by JoeLoser** [comment]
Landed in today's nightly release via https://github.com/modularml/mojo/commit/e6d161c276fa64877dafbb7017eaa181dae20430!

**Pull request closed without merging**
