### PR TITLE
[stdlib] add benchmark for lcm and gcd

### PR DESCRIPTION
**Pull request by bgreni**
Add benchmarks for `lcm` and `gcd` functions

### CODE REVIEW

**Review by JoeLoser — COMMENTED** [review]
!sync

**Comment by JoeLoser** [comment]
!sync

**Comment by soraros** [comment]
They are moved to `math`.

**Comment by JoeLoser** [comment]
When importing this and playing with it (and adding a necessary `benchmark.keep` call to the function), it hit a compiler error.  I filed an issue internally, but this is blocked until then.

**Pull request closed without merging**
