### PR TITLE
[stdlib] Make `StringSlice` `CollectionElement`

### PR DESCRIPTION
**Pull request by martinvuyk**
Make `StringSlice` `CollectionElement`

### CODE REVIEW

**Comment by soraros** [comment]
Can we simply use `@value` here?

**Comment by martinvuyk** [comment]
HI @soraros. I'm seeing that `Span` uses `@value` but it's components are just an `UnsafePointer` and an `Int`, so if we used `@register_passable("trivial")` here it would need to be changed as well. BTW I also still don't quite understand the difference between `@register_passable("trivial")` and plain `@register_passable`. WDTY?

**Comment by soraros** [comment]
@martinvuyk I'm not sure either. Let's wait for the team to respond.

**Review by JoeLoser — APPROVED** [review]

**Comment by martinvuyk** [comment]
@JoeLoser fixed the merge conflict but the CI keeps failing on `error: cannot open input file '/home/runner/work/mojo/mojo/stdlib/scripts/check-licenses.mojo` for this and other PRs

**Comment by JoeLoser** [comment]
!sync

**Pull request closed without merging**
