### PR TITLE
[stdlib] Add `Span[Scalar[D]].__contains__()`

### PR DESCRIPTION
**Pull request by martinvuyk**
Add `Span[Scalar[D]].__contains__()`

### CODE REVIEW

**Comment by lsh** [comment]
!sync

**Comment by lsh** [comment]
Closing as this made it into the latest release.

**Comment by martinvuyk** [comment]
@lsh not sure what the Modular internal tooling (copybara) entails, but FYI commit c61a7ad6e914ab2d8757cb8b60ed78237c91ac15 didn't have my authorship info, and normally modularbot also handles the closing of PRs.

**Comment by lsh** [comment]
@martinvuyk Ah sorry about that. I'll look into it

**Pull request closed without merging**
