### PR TITLE
[mojo-stdlib] implement all divs on object

### PR DESCRIPTION
**Pull request by jiex-liu**
see #2224

### CODE REVIEW

**Comment by StandinKP** [comment]
@LJ-9801 can you add a test case for this? Would be good to have

**Comment by LJ-9801** [comment]
yeah I will, this is just a draft pr. There are probably other methods I need to implement as well. Thank you for the notice!

**Review by JoeLoser — APPROVED** [review]
Great, thank you for working on this! 🎉

**Comment by JoeLoser** [comment]
@LJ-9801 do you mind fixing up the merge conflict?  After that, happy to land this.  Thank you!

**Comment by LJ-9801** [comment]
@JoeLoser thank you for the reminders! all conflicts are resolved.

**Comment by JoeLoser** [comment]
> @JoeLoser thank you for the reminders! all conflicts are resolved.

Merged, thank you for the contribution! 🔥 🎉

**Pull request merged**
