### PR TITLE
[stdlib] Remove some `# CHECK` and refactor `test_print.mojo`

### PR DESCRIPTION
**Pull request by gabrieldemarmiesse**
Related to #2024 

Some tests in `test_print.mojo` are not related to printing at all. It's more testing the string conversion. So I took the liberty of putting them in the right files. This also helped remove some `# CHECK` as removing those when testing the print() function is really hard.

### CODE REVIEW

**Review by ConnorGray — APPROVED** [review]
Thanks for this, this is a nice cleanup!

This LGTM, but as mentioned on another one your PRs, I'll hold off on merging temporarily until tomorrow when we've wrapped up an internal infrastructure migration.

**Comment by ConnorGray** [comment]
Hey @gabrieldemarmiesse we have our new merging infrastructure set up, but in order to merge this branch it will need to be rebased to include the "baseline" commit that our new syncing tool uses.

Could you:

```
# Ensure you have the latest `nightly` branch update
$ git checkout nightly
$ git pull

# Rebase your branch so its history includes all of `nightly`
$ git checkout <this PRs branch>
$ git rebase nightly
```

This will ensure this branch includes [this baseline commit](https://github.com/modularml/mojo/commit/684efe5e3f11508ffa177b5b3371c3978d1d8f57) in its history.

Once this is done, I'll be able to proceed with merging this PR 🙂

Thank you in advance, and apologies for the wait!

**Comment by gabrieldemarmiesse** [comment]
Sure thing. I'll do it for all my PRs in one go :)

**Comment by ConnorGray** [comment]
Perfect, thank you so much! 🙌

**Comment by gabrieldemarmiesse** [comment]
All PRs rebased :)

**Comment by ConnorGray** [comment]
**✅🟣 This contribution has been merged 🟣✅**

Hi @gabrieldemarmiesse for this contribution, and updating all of your PRs!

As mentioned, we're moving to a new infrastructure for merging contributions to Mojo (we're using a tool called [Copybara](https://github.com/google/copybara)), and your contribution has now been merged into our internal copy of the Mojo Standard Library.

The changes in this PR will appear here in the mojo repo `nightly` branch when we do our next outbound synchronization at the time that the next Mojo nightly is released. That should happen later today but could be delayed until Monday.

Thank you so much for helping us burn down 🔥 the `FileCheck` uses! :)

Please let me know if you have any questions or concerns.

**Comment by gabrieldemarmiesse** [comment]
Thanks for all the work around making the nightly available more frequently!

While this is great to see much faster the internal commits publicly, we will see the external commits be updated every 24 hours if I understand correctly. This can be a big pain if we have multiple pull requests touching the same piece of code, we can do only one rebase every 24 hours. Would it be possible to refresh the public branch as frequently as possible? If possible every commits if this is automatic? Otherwise making PRs that depends on other PRs will be a pain (and it's also more difficult to develop if we can't see which PR has merged during the day and we can't pull those changes).

**Pull request closed without merging**
