### PR TITLE
[stdlib] List.__eq__ and List.__ne__ for Rhs_t:EqualityCollectionElement

### PR DESCRIPTION
**Pull request by gabrieldemarmiesse**
@rd4com  should be credited for this work. I just fixed git conflicts and moved a few things around. See 

* https://github.com/modularml/mojo/pull/2702

which has the original implementation.

### CODE REVIEW

**Comment by rd4com** [comment]
@gabrieldemarmiesse good job and thanks for the complementary effort,
it is a hard one, we'll get there one day for the sugar,
:tada: :+1: happy that `.__eq__()` and `.__ne__()`  works !

**Comment by JoeLoser** [comment]
!sync

**Comment by JoeLoser** [comment]
!sync

**Comment by JoeLoser** [comment]
Thanks for continuing to push on this!  This is crashing the parser internally still, so we'll need to dig into it.  FYI we're all away for a company onsite this week, so it will likely be a next week thing.

**Comment by JoeLoser** [comment]
> Thanks for continuing to push on this! This is crashing the parser internally still, so we'll need to dig into it. FYI we're all away for a company onsite this week, so it will likely be a next week thing.

Here'a a snippet of the crash in case @Mogball or @laszlokindrat know a workaround:

```
<unknown>:0: error: 'inferred' parameter follows non-inferred parameter
Assertion failed: (succeeded(ConcreteT::verify(getDefaultDiagnosticEmitFn(ctx), args...))), function get, file StorageUniquerSupport.h, line 181.
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.

Crash resolving decl signature at loc("/Users/joe/dev/modular/open-source/mojo/stdlib/stdlib/collections/list.mojo":868:8)
    >>     fn __eq__[
              ^......
    >>         ElementType: EqualityCollectionElement, //
    >>     ](self: List[ElementType], rhs: List[ElementType]) -> Bool:
```

**Comment by gabrieldemarmiesse** [comment]
@JoeLoser maybe it's because of a very recent commit done after today's nightly?

**Comment by laszlokindrat** [comment]
> Here'a a snippet of the crash in case @Mogball or @laszlokindrat know a workaround:
> 
> ```
> <unknown>:0: error: 'inferred' parameter follows non-inferred parameter
> Assertion failed: (succeeded(ConcreteT::verify(getDefaultDiagnosticEmitFn(ctx), args...))), function get, file StorageUniquerSupport.h, line 181.
> Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
> 
> Crash resolving decl signature at loc("/Users/joe/dev/modular/open-source/mojo/stdlib/stdlib/collections/list.mojo":868:8)
>     >>     fn __eq__[
>               ^......
>     >>         ElementType: EqualityCollectionElement, //
>     >>     ](self: List[ElementType], rhs: List[ElementType]) -> Bool:
> ```

Looks like a legit compiler bug. Probably somewhere we prepend parameters but don't use the correct passing kind. Please file a ticket.

**Comment by ConnorGray** [comment]
FYI that I filed a ticket with the compiler team to track this internally.

**Comment by JoeLoser** [comment]
Closing this since https://github.com/modularml/mojo/pull/3195 just landed!  Thanks!

**Pull request closed without merging**
