### PR TITLE
[docs] `entr` and pre commit issue

### PR DESCRIPTION
**Pull request by artemiogr97**

### CODE REVIEW

**Comment by artemiogr97** [comment]
"solves" #2528

**Review by JoeLoser — APPROVED** [review]
Looks good. Do people like the entr section at all? If we're just documenting sharp edges with it, does it make sense to put it in the contributing guide at all?

**Comment by artemiogr97** [comment]
personally I really like it, I've been using it since I started contributing some weeks ago, I don't know how I managed to avoid the issue for so long 🤷‍♂️

**Comment by JoeLoser** [comment]
Landed in today's nightly: https://github.com/modularml/mojo/pull/2605.  Thanks for the contribution! 🎉

**Pull request closed without merging**
