### PR TITLE
[docs] Fix minor typos in API doc strings

### PR DESCRIPTION
**Pull request by JalinWang**

### CODE REVIEW

**Review by scottamain — APPROVED** [review]
Thank you!

**Review by JoeLoser — CHANGES_REQUESTED** [review]
Thanks for the fix!  Do you mind adding a signed-off part to your commits per the [docs](https://github.com/modularml/mojo/blob/main/CONTRIBUTING.md#signing-your-work)?

Additionally, we want to have this PR target the `nightly` branch and not the `main` branch as discussed [here](https://github.com/modularml/mojo/blob/main/CONTRIBUTING.md#pull-requests).  Do you mind rebasing with the `nightly` branch and updating the `base` branch in this PR?  To do that, you can click the "edit" button at the top of this PR.

**Comment by JalinWang** [comment]
Oops I had read the guidance and noticed the branch convention. However, it turns out I still missed it in the end 😥 sorry for my bad

**Comment by JalinWang** [comment]
@JoeLoser Done. Sorry again for causing trouble 😫

**Comment by JalinWang** [comment]
@MertCelik Hi~ It seems like this PR only contains one signed commit ? 🤔
image

**Review by JoeLoser — APPROVED** [review]

**Pull request merged**
