### PR TITLE
[stdlib] Cleanup `polynomial.mojo`, improve docstring

### PR DESCRIPTION
**Pull request by soraros**
- Small simplification to the function `_horner_evaluate`.
- Improve its docstring to match the argument names.
- ~~Finish off removing `unroll` by cleaning up the imports.~~

### CODE REVIEW

**Review by JoeLoser — APPROVED** [review]
Looks good, thank you!  Do you mind fixing up the merge conflicts and then I'm happy to merge this?

**Comment by soraros** [comment]
@JoeLoser It seems that Abdul already removed the `unroll` in a1cba9d. I think the cleanup is still worthwhile, but I will let you decide.

**Comment by JoeLoser** [comment]
> @JoeLoser It seems that Abdul already removed the `unroll` in [a1cba9d](https://github.com/modularml/mojo/commit/a1cba9dbe5a5335a120fb29d1b1b03cf0bd73578). I think the cleanup is still worthwhile, but I will let you decide if we still want to merge this.

+1 to the cleanup.  Mind retitling the PR/description to match the current cleanup then?  Thanks!

**Comment by JoeLoser** [comment]
!sync

**Review by JoeLoser — APPROVED** [review]

**Comment by JoeLoser** [comment]
> This should be a trivial cleanup, however, inlining `c_second_from_last` seems to be causing the problem. As can be seen in [this CI run](https://github.com/modularml/mojo/actions/runs/9898343074/job/27344926519?pr=3222), `coefficients[-2]` is somehow changed after the first access.
> 
> This is the output of the following code:
> 
> ```mojo
> print("alias", c_second_from_last, coefficients[num_coefficients - 2])
> ```
> 
> ```
> ...
> alias -0.11514610052108765 1.7441815041421925e+28
> alias 0.0013888889225199819 8.5597826238818937e-39
> alias -0.11514610052108765 1.7441815041421925e+28
> alias 0.0013888889225199819 8.5597826238818937e-39
> alias -0.11514610052108765 1.7441815041421925e+28
> alias 0.0013888889225199819 8.5597826238818937e-39
> alias -0.11514610052108765 1.7441815041421925e+28
> alias 0.0013888889225199819 8.5597826238818937e-39
> ...
> ```

Can you file a compiler bug for this, please?

**Review by JoeLoser — COMMENTED** [review]
In order to not have this be blocked by the compiler bug, I'm going to to merge the docstring cleanups here and leave the body as-is.

**Comment by JoeLoser** [comment]
!sync

**Comment by soraros** [comment]
@JoeLoser I think the bug is also caused by compile time usage of `List`, tracked in #3126.

**Comment by JoeLoser** [comment]
> @JoeLoser I think the bug is also caused by compile time usage of `List`, tracked in #3126.

Makes sense, yeah. Chris is looking at that bug.

**Pull request closed without merging**
