### PR TITLE
[stdlib] Rename `Arc.as_ptr()` to `Arc.unsafe_ptr()` and document safe dereferencing (`[]`)

### PR DESCRIPTION
**Pull request by rd4com**
Hello, here is a patch toward removing a foot gunner for users.

Mojo's ASAP deletion policy works really well,
users might unsafely dereference the `Arc._inner` field,
only to find out that mojo already freed the pointer ! :rocket: 

We might understand and love ASAP, but users need :shield: safeguards !

With this patch, 
people are encouraged to use the `Lifetime` dereference subscript `[]`.

It also includes further educating by expanding the documentation of `Arc` .

Left a `TODO: remove this method` on `Arc.unsafe_ptr()`, in order to not forget.

it is recommended to consider removing this method.

### CODE REVIEW

**Review by JoeLoser — APPROVED** [review]

**Comment by JoeLoser** [comment]
!sync

**Comment by ConnorGray** [comment]
Thank you for adding the documentation clarifying how this can be VERY unsafe!

I suggest though that instead of removing this method entirely, we rename it to `unsafe_ptr()` to make its unsafety clear to potential users, and for consistency with the standardized naming of the many other `unsafe_ptr()` methods in the standard library.

**Comment by rd4com** [comment]
@ConnorGray @JoeLoser ,
changes suggested have been made :partying_face: 
I left a `TODO: remove this method` (in order to not forget) !?

**Comment by JoeLoser** [comment]
!sync

**Review by JoeLoser — APPROVED** [review]

**Pull request closed without merging**
