### PR TITLE
[mojo-stdlib] Fix `len` for unary `range` with negative `end` value

### PR DESCRIPTION
**Pull request by soraros**
I think we could simply `_ZeroStartingRange` and use `_SequentialRange`.

### CODE REVIEW

**Review by JoeLoser — COMMENTED** [review]
Looks good, thanks!  You'll just need to rebase to resolve the conflict.  Did you explore removing `_ZeroStartingRange` entirely in favor of using `_SequentialRange`?

**Review by JoeLoser — APPROVED** [review]

**Comment by helehex** [comment]
[This was also mentioned here](https://github.com/modularml/mojo/pull/2215#issuecomment-2040965747)

**Comment by soraros** [comment]
@JoeLoser I'd like to explore removing `_ZeroStartingRange` first.

**Comment by JoeLoser** [comment]
@soraros do you mind running `mojo format` on the test file and committing please?  I was trying to be helpful and resolved your merge conflict in the UI but it introduced a `mojo format` issue.  Sorry about that — figured I'd give it a try since the rebase was trivial rather than bothering you with a back-and-forth on it. After that, happy to merge.  Thanks.

**Pull request merged**
