### PR TITLE
[stdlib] `normalize_index()` usage in `vector.mojo`

### PR DESCRIPTION
**Pull request by MatveyF**
Using `normalize_index` to reduce boilerplate bounds checking.

Related to #2948

### CODE REVIEW

**Review by gabrieldemarmiesse — COMMENTED** [review]
That looks good! Thanks for the pull request, it's a nice cleanup!

**Comment by JoeLoser** [comment]
Looks good, thanks for the cleanup!  Do you mind fixing up the merge conflicts and then I'm happy to import this PR and land it?

**Review by JoeLoser — APPROVED** [review]

**Comment by JoeLoser** [comment]
!sync

**Comment by JoeLoser** [comment]
Thanks for the contribution! Our team is working on some broader changes to bounds checking which may also touch on negative indexing and avoiding runtime costs associated with this where desired.

So, for now, to help clean up the pull request review queue, instead of this hanging out for a while like it has, I'm going to close this pull request and we can see where things settle in the coming weeks to see if this is still an issue. Again, I appreciate your enthusiasm in helping make the standard library better! 🔥

**Pull request closed without merging**
