### PR TITLE
[mojo-stdlib]Use variadic initializer of `List` in tests

### LINKED ISSUE #2045: [mojo-stdlib] Make use of variadic initializer for `List` where applicable
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

For example, replace things like 

```mojo
var l = List[String]()
l.append("one")
l.append("two")
l.append("three")
```

with 

```mojo
var l = List[String]("one", "two", "three")
```

This is a bit shorter and easier to read.  One such example is [here](https://github.com/modularml/mojo/blob/4feb92e8106072a7d9929cba9eee220422afb227/stdlib/test/collections/test_list.mojo#L133C5-L136C25)

### What is your motivation for this change?

Using new standard library constructor for `List` to simplify/shorten existing code.

### Any other details?

_No response_

### PR DESCRIPTION
**Pull request by MertCelik**
Fixes https://github.com/modularml/mojo/issues/2045

### CODE REVIEW

**Review by JoeLoser — DISMISSED** [review]
Looks good, thanks!  We could also apply this in `stdlib/test/utils/issue_13632.mojo` too if you're up for it in a future PR.

**Comment by JoeLoser** [comment]
@MertCelik Before we can merge, could you confirm that you've agreed to Developer Certificate of Origin, by including the Signed-off-by signature in your commit, as [described in the contributor guide](https://github.com/modularml/mojo/blob/main/CONTRIBUTING.md#signing-your-work)?

I just enabled the repository setting that ensures the commit(s) are signed off.  It may be easiest to squash your commits and then add the sign off part to the final one commit.  You can do this with:

```
git remote -v # is your <remote> below upstream corresponding the modularml/mojo repo?
git rebase -i <remote>/nightly # interactive rebase
# Select the s for squashing your commits into the one final commit
# Select r to reword your commit and add the signed-off part.
git push (Note: may need to force push here in this case)
```

Feel free to reach out if you run into any issues and I'm happy to help.

Once that's in place we should be good to go—thanks again for helping us improve the Mojo🔥 standard library!

**Comment by MertCelik** [comment]
> Looks good, thanks! We could also apply this in stdlib/test/utils/issue_13632.mojo too if you're up for it in a future PR.

Thanks for the catch! Just included in this PR.

> @MertCelik Before we can merge, could you confirm that you've agreed to Developer Certificate of Origin, by including the Signed-off-by signature in your commit, as [described in the contributor guide](https://github.com/modularml/mojo/blob/main/CONTRIBUTING.md#signing-your-work)?

@JoeLoser Let me know if I made it correctly!

**Review by JoeLoser — APPROVED** [review]
Thanks for the contribution! 🔥

**Pull request merged**
