### PR TITLE
[mojo-stdlib] Import what you use rather than `from <module> import *`

### LINKED ISSUE #2043: [mojo-stdlib] Import what you use rather than `from <module> import *`
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

In general, wildcard imports aren't great for a variety of reasons.  In our [style guide](https://github.com/modularml/mojo/blob/nightly/stdlib/docs/style-guide.md#import-statements) we mention to avoid `import *`.  So, it would be nice to audit (and fix) where we still use `import *` in the source code of the standard library and replace it with explicit imports of the entities (functions, aliases, etc.) used in that file.  

### What is your motivation for this change?

Adhere to style guide.

### Any other details?

Related to https://github.com/modularml/mojo/issues/2023, recommend we do https://github.com/modularml/mojo/issues/2023 first to avoid conflicts.

Should we make a special case for `from testing import *` in test files?  By definition, since test files are "leafs" in a build target graph, we won't leak symbols downward, for example.

### PR DESCRIPTION
**Pull request by StandinKP**
Fixes #2043

### CODE REVIEW

**Comment by gabrieldemarmiesse** [comment]
Hi, thank you for the pull request. It seems that the DCO is missing (the "signed-off-by" in commits). Please head to https://github.com/modularml/mojo/blob/main/CONTRIBUTING.md#signing-your-work and rectify the commit messages.

**Comment by StandinKP** [comment]
> Hi, thank you for the pull request. It seems that the DCO is missing (the "signed-off-by" in commits). Please head to https://github.com/modularml/mojo/blob/main/CONTRIBUTING.md#signing-your-work and rectify the commit messages.

@gabrieldemarmiesse is this to be done for all commits or just should i add it to the last commit?

**Comment by gabrieldemarmiesse** [comment]
I believe it must be done on all commits

**Comment by StandinKP** [comment]
Got it. Thanks. I have updated the commits

**Comment by JoeLoser** [comment]
The changes themselves look good, thank you!  Just need to fix up the formatting: 

```
mojo format -l 80
stdlib/test/builtin/test_simd.mojo
stdlib/test/builtin/test_string.mojo
stdlib/test/collections/test_set.mojo
stdlib/test/memory/test_memory.mojo
stdlib/test/pathlib/test_pathlib.mojo
stdlib/test/test_utils/types.mojo
stdlib/test/utils/test_tuple.mojo
stdlib/test/utils/test_variant.mojo
```

should do the trick for you.

**Review by JoeLoser — APPROVED** [review]

**Pull request merged**
