### PR TITLE
[stdlib] Add `sqrt(FloatLiteral) -> FloatLiteral` overload.

### PR DESCRIPTION
**Pull request by helehex**
Add `FloatLiteral.__sqrt__()`
Add `FloatLiteral.__recip_sqrt__()`
Add Newtons method for solving it.

I hope this doesn't explode anyone's compile times, but since i did #3381 I figured I should add this as well.

### CODE REVIEW

**Comment by helehex** [comment]
There's worse things you could already do at compile time, right? It'll be finee...

**Comment by helehex** [comment]
If it is a problem, I could get rid of the `sqrt()` overload, but keep the `FloatLiteral__sqrt__()` method so we still have something. Then we can improve the implementation over time. same for #3381

**Review by JoeLoser — COMMENTED** [review]
Similar comments about the use of special dunder methods as my comments from https://github.com/modularml/mojo/pull/3381#issuecomment-2305320989.  @abduld how do you feel about introducing a Newton solver in the math module?  I'm not so sure we want to go down that route right now in the standard library.

**Comment by helehex** [comment]
The dunder would gives a nice handle for a sqrtable trait, and yeah I'm not sure about the newton solver either, but it's what I had on hand, and I realized that having a intliteral sqrt and not a floatliteral sqrt might cause issues, so I just did both

**Comment by helehex** [comment]
Also, i know someone was asking about floatliter/intliteral square root in one of the community meetings, and since i already made them for one of my projects, i figured i'd try adding them. (which is another reason this would be nice; a sqrtable trait would avoid conflics with builtin sqrt that i've have to work around in that project)

**Comment by helehex** [comment]
Closing until we have better benchmarks

**Pull request closed without merging**
