### PR TITLE
[stdlib] Add __bool__() for InlineList

### PR DESCRIPTION
**Pull request by northstreet12**
This PR adds __bool__() for InLineList, which checks whether the list has any elements or not.

### CODE REVIEW

**Review by gabrieldemarmiesse — APPROVED** [review]
Thank you! This looks good!

**Review by JoeLoser — APPROVED** [review]

**Comment by JoeLoser** [comment]
!sync

**Comment by northstreet12** [comment]
> !sync

Is it ok now?

**Comment by JoeLoser** [comment]
!sync

**Pull request closed without merging**
