### PR TITLE
[mojo-stdlib][docs] Update docs and code to use `from <module> import <entity>` instead of `from <module>.<file> import <entity>` new

### PR DESCRIPTION
**Pull request by FarhanAliRaza**
Fixes https://github.com/modularml/mojo/issues/2023
Old PR had gotten out of hand.
Sorry for causing this issue

### CODE REVIEW

**Review by JoeLoser — APPROVED** [review]
Still looks great to me!  Do you mind rebasing to resolve the few (three) file conflicts?  Once that is taken care of, I'll make sure to merge this ASAP so you avoid future merge conflicts since this touches pretty much every file. 😄

**Comment by FarhanAliRaza** [comment]
@JoeLoser  is it ready to merge?

**Comment by JoeLoser** [comment]
> @JoeLoser is it ready to merge?

Yep, I'll merge this first thing when I'm back by a laptop later today 😊

**Comment by JoeLoser** [comment]
> > @JoeLoser is it ready to merge?
> 
> Yep, I'll merge this first thing when I'm back by a laptop later today 😊

@FarhanAliRaza just merged — thanks so much for pushing on this and your contribution! 🎉

**Comment by FarhanAliRaza** [comment]
Thank you @JoeLoser and @ConnorGray for your support.

**Pull request merged**
