### PR TITLE
[stdlib] Extend tests for `SIMD.__pow__`

### PR DESCRIPTION
**Pull request by jjvraw**
Partially addresses Issue #2867

### CODE REVIEW

**Review by laszlokindrat — COMMENTED** [review]
Thanks, generally looks great, and welcome to Mojo! :) Looks like you have a lot of tests for the `__pow__` overload that takes an `Int`, but no unit tests where the power is another non-scalar SIMD vector. Could you please add some, or maybe modify some of the existing ones? Also, it would be good to have some tests involving `neg_zero`.

**Comment by jjvraw** [comment]
Hi :) 

Added a few additional test cases, and removed a few unnecessary ones. Happy to adjust further if needed.

**Review by laszlokindrat — APPROVED** [review]
Great, thank you!

**Comment by laszlokindrat** [comment]
!sync

**Pull request closed without merging**
