### PR TITLE
[stdlib] tempfile and tempdir

### PR DESCRIPTION
**Pull request by artemiogr97**
Implementation for #2018

### CODE REVIEW

**Comment by artemiogr97** [comment]
I opened the pull to have some feedback, some points to discuss:

- Are the read methods useful ?
  - personally I don't know in which case I would create a temporary file and read from it at the same time
- should I implement what I need in the os module directly in this pull ?
  - `TemporaryDirectory` is not implemented yet because `os.mkdir` and `os.rmdir` don't exist, I guess `shutil.rmtree` will be necessary too
  -  For `NamedTemporaryFile` there is a slight difference with respect to the python implementation, the name attribute could end up being relative but the functions `os.abspath`, and `os.normpath` still don't exist
     - also how different platforms are going to be handled in mojo, in python there are dedicated modules `posix` and `ntpath`, I guess the same should be done in mojo?

**Comment by artemiogr97** [comment]
#2439 must be merged first

**Comment by JoeLoser** [comment]
> #2439 must be merged first

Sorry for the delay here.  Is it possible to decouple this PR from #2439?  I think temporary file things would be useful even outside of the `rmtree` functionality, so I'd rather not couple them.

FYI @laszlokindrat @Dan13llljws @ConnorGray as we were talking about temp files today.

**Comment by laszlokindrat** [comment]
> Sorry for the delay here. Is it possible to decouple this PR from #2439? I think temporary file things would be useful even outside of the `rmtree` functionality, so I'd rather not couple them.

I completely agree. Can you please rebase this on the latest nightly, and maybe start splitting it up? Also one concrete suggestion: could you please start with the low level `tempfile` APIs, i.e. `gettempdir` and `mkdtemp`, and maybe `mkstemp`, and then we can build the rest on it.

This super cool, we're super happy that you are pushing this forward!

**Comment by artemiogr97** [comment]
> could you please start with the low level `tempfile` APIs, i.e. `gettempdir` and `mkdtemp`, and maybe `mkstemp`, and then we can build the rest on it.
@laszlokindrat I started working on this, I'm having some issues with `mkstemp`, in python it returns a tuple with the file object and the name, I'm not sure how to do this in mojo, the problem is that when I do the following I have an error:
```
tmp_file_and_name = msktemp()
tmp_file = tmp_file_and_name[0]  # error here: 'FileHandle' is not copyable because it has no '__copyinit__'
file_name = tmp_file_and_name[1]
```
I tried doing `tmp_file = tmp_file_and_name.get[0, FileHandle]()` but then I have a double free at runtime.
I guess that the best option is to return only the file handle for now? but we wont have access to the file name

**Comment by artemiogr97** [comment]
I opened a new PR (#2742) that implements `gettempdir` and `mkdtemp`, and a second PR ( #2743) for `TemporaryDirectory` using `mkdtemp`

**Comment by artemiogr97** [comment]
@JoeLoser, @laszlokindrat  I opened another PR #2762 for `NamedTemporaryFile` seems so be easier to implement than `mkstemp` for now, I opened it as a draft since I'm having some issues, I'll leave you all the details in that PR.

Also I guess I can close this PR and also #2439 since everything is now splitted in #2742, #2743 and #2762

**Pull request closed without merging**
