### PR TITLE
[stdlib] Move `InlineArray` into collections module

### PR DESCRIPTION
**Pull request by helehex**
Move `InlineArray` into `/stdlib/collections/`.
Remove unnecessary imports and corresponding TODO's

### CODE REVIEW

**Review by JoeLoser — COMMENTED** [review]
**Suggestion** Can we split this PR up a bit, please?  Let's do the file move(s) for `inline_array` into `collections` in the first PR in the stack.  It will require some fixups internally and I will do that immediately when that is ready and we can work on the rest.

**Comment by helehex** [comment]
sure, gimme a little bit

**Comment by helehex** [comment]
i'm also moving the tests into the right place since i forgot todo that

**Comment by helehex** [comment]
I knew going in i should've at least left it in two commits, but it's ok i got it.

**Comment by helehex** [comment]
did you do it, or busy with other things now @JoeLoser ?

**Comment by JoeLoser** [comment]
!sync

**Comment by JoeLoser** [comment]
> did you do it, or busy with other things now @JoeLoser ?

I synced it after your latest round of pushes (it gets synced internally when I post a !sync comment like I did at https://github.com/modularml/mojo/pull/3363#issuecomment-2272254832).  I'm fixing up the internal breakage from the file move and then this will be able to land to unblock your other work you want to do in this area.  Thanks for your patience!

**Comment by helehex** [comment]
Did it just sync again? You got a thumbs up :]

**Comment by JoeLoser** [comment]
> Did it just sync again? You got a thumbs up :]

Lol, it did since the internal tool just searches for that phrase when mentioned by a Modular employee.  It's smart enough to rebase though since I had pushed to the internal branch/PR.  In any case, it just landed and will be available in the next nightly.  Thank you for doing this! 😄

**Pull request closed without merging**
