### PR TITLE
[stdlib] Rename `InlinedFixedVector` to `Vector`

### PR DESCRIPTION
**Pull request by martinvuyk**
First stage to renaming `InlinedFixedVector` to `Vector` as per issue #2773

### CODE REVIEW

**Comment by helehex** [comment]
i would like if vector would eventually refer to a safe wrapper around dtype pointer

**Comment by helehex** [comment]
I believe theres a chance DTypePointer will get deprecated eventualy but im not sure

**Comment by martinvuyk** [comment]
> i would like if vector would eventually refer to a safe wrapper around dtype pointer, but this is probably good, at least for now

I'm not sure if that's even possible since in theory you could try to alloc something larger than your available heap

**Review by JoeLoser — CHANGES_REQUESTED** [review]
I'm not a big fan of this change right now.  I'd rather us push `CollectionElement` through to this collection before we name it something more generic.  The bad name shys people away from this type intentionally right now still.

Also, do we even need this type once our `List` type supports small buffer optimization?  See https://github.com/modularml/mojo/pull/2613 from @gabrieldemarmiesse.

**Comment by gabrieldemarmiesse** [comment]
Yep, I don't see any use cases of InlinedFixedVector in the future, if my proposal for small buffer optimisation get through, that is. I'm unsure of the general feelings of the maintainers on the subject.

**Comment by martinvuyk** [comment]
Hadn't seen that PR, makes sense.

**Pull request closed without merging**
