### PR TITLE
[stdlib] Add `sqrt(IntLiteral) -> IntLiteral`.

### PR DESCRIPTION
**Pull request by helehex**
I know there are better methods, but it would be nice to have something.
I'm not sure there's a nice way to track compile time benchmarks in the stdlib right now, so that might have to wait.

### CODE REVIEW

**Comment by helehex** [comment]
I move the tests into `/test_intliteral.mojo` instead of `/test_math.mojo`

**Comment by JoeLoser** [comment]
Can you help provide some context as to why we'd want to use a `__sqrt__` dunder method?  There's no Python precedence for this as @laszlokindrat kindly pointed out to me offline.  _If_ we were to define a dunder method (although it opens the question of do we even want to go down that route for ones Python doesn't define), we should be intentional about it, and likely introduce a corresponding trait for it.

Given the existing `math.sqrt(Int)` function, I could imagine putting an `IntLiteral` overload next to it.  What do you think, @abduld?

**Comment by helehex** [comment]
if we change to using `isqrt` to mean integer square root this should probably be rethought as well.

**Comment by helehex** [comment]
Oh yeah, having it be a method in `IntLiteral` makes the tests more explicit too

**Comment by helehex** [comment]
Closing until we have better benchmarks.

**Pull request closed without merging**
