### PR TITLE
[docs] Fix typo in changelog.md

### PR DESCRIPTION
**Pull request by Brian-M-J**
Change "complexify" to "complicate"

### CODE REVIEW

**Review by JoeLoser — COMMENTED** [review]
@arthurevans thoughts here?  "complexify" is indeed a word, so I don't feel strongly here.

**Review by arthurevans — APPROVED** [review]
As @JoeLoser pointed out (to my surprise), the OED says that complexify is actually a word. It also says that it basically means the same thing as complicate, which is 100 times as common in English. 

so unless I'm missing an important distinction here that's specific to programming language or compiler design, for example, I'd take the more common word.

**Comment by JoeLoser** [comment]
!sync

**Comment by Brian-M-J** [comment]
> As @JoeLoser pointed out (to my surprise), the OED says that complexify is actually a word.

This is a surprise to me as well.

**Pull request closed without merging**
