### PR TITLE
[stdlib] Add `lstrip()` and `rstrip()` to `StringRef`

### PR DESCRIPTION
**Pull request by fknfilewalker**
`lstrip` and `rstrip` for `StringRef`, and delegates `String.rstrip` and friends to this `StringRef` implementation.

### CODE REVIEW

**Comment by fknfilewalker** [comment]
@JoeLoser

**Comment by JoeLoser** [comment]
> @JoeLoser

Thanks for the ping, I'll TAL when I'm by a laptop soon, likely later today.

**Review by JoeLoser — COMMENTED** [review]
Want to add some explicit tests for StringRef with these functions?

**Comment by fknfilewalker** [comment]
> Want to add some explicit tests for StringRef with these functions?

I could copy the tests from string over, or do you have something better in mind?

**Comment by JoeLoser** [comment]
> > Want to add some explicit tests for StringRef with these functions?
> 
> I could copy the tests from string over, or do you have something better in mind?

I don't have anything better in mind, but I think that's what we've been doing with other recent PRs (although not consistently from a quick glance).  It adds minimally more test coverage.  What do you think?

In general, with all of this work in pushing `String` methods down to `StringRef`, maybe we should move a lot of `String` methods onto `StringSlice` instead, and on `String` have it internally take itself as a slice and do the operation?  This was mentioned by @lsh offline the other day.

**Comment by JoeLoser** [comment]
Are you still interested in finishing this work to get it over the finish line?

**Comment by fknfilewalker** [comment]
Ok, I accidentally closed this pr when I reset my branch to the nightly latest changes... I'll just open a new one, in case I implement this.

**Pull request closed without merging**
