### PR TITLE
Update functions.ipynb

### PR DESCRIPTION
**Pull request by ratulb**
Typo - current to currently.

### CODE REVIEW

**Comment by arthurevans** [comment]
Thanks for the fix @ratulb ... Can you target this change against the nightly branch as described in the [Contribution guide](https://github.com/modularml/mojo/blob/main/CONTRIBUTING.md#branching-off-nightly)?

**Comment by ratulb** [comment]
Changed upstream to nightly as advised.

**Comment by arthurevans** [comment]
Hi @ratulb. Sorry, to target nightly you have to start from nightly. So this PR as it stands would merge the (old) stuff from main on top of the (new) stuff in nightly--that's why all of these commits are showing up.

If you made the change on a local machine using the github command-line, it's pretty easy to create a new branch based off nightly and cherry-pick the single commit over. But it looks like this commit was done directly in the GitHub UI, and I'm not sure if there's an easy way to fix it up. It might be easier to recreate this commit on the nightly branch.

**Comment by Brian-M-J** [comment]
The [fix](https://github.com/modularml/mojo/commit/7e0a0a974328ae2554c23c98a6798c061e97f175#diff-c8454eeb991c1790a667a1364d719ac573cd8c85241caa37e91161a9181a3ca9L353) has already been applied in the `nightly` branch; see [commit 565586f](https://github.com/modularml/mojo/commit/565586fcda0b7b0db4a40efe593af28618bd6589#diff-c8454eeb991c1790a667a1364d719ac573cd8c85241caa37e91161a9181a3ca9L350).

**Pull request closed without merging**
