### PR TITLE
Update types.ipynb

### PR DESCRIPTION
**Pull request by nw31304**
Minor typo corrections

### CODE REVIEW

**Review by KenJones-Modular — APPROVED** [review]

**Comment by JoeLoser** [comment]
Thanks for the fix.  Do you mind targeting the nightly branch instead as the [docs](https://github.com/modularml/mojo/blob/nightly/CONTRIBUTING.md#pull-requests) say?  Otherwise, we won't be able to import this PR and merge it.

**Comment by Brian-M-J** [comment]
The [second typo fix](https://github.com/modularml/mojo/pull/2512/files#diff-013bed940feb94fa25ae4e5d30fb4b4fd45718daaf87a47d81043fc5181c618aL823) has already been applied in the `nightly` branch by someone else; see [commit 2d015fb](https://github.com/modularml/mojo/commit/2d015fb549fc3c1efd4312abc749066aaf66ea9c#diff-013bed940feb94fa25ae4e5d30fb4b4fd45718daaf87a47d81043fc5181c618aL834).

I suggest you quickly rebase your branch on top of `nightly` to at least get your first fix in before someone else does. See [here](https://github.com/modularml/mojo/pull/2694#issuecomment-2129767689) for some suggestions on how to do so.

**Comment by Brian-M-J** [comment]
The first fix has also been applied in #2818.

**Comment by nw31304** [comment]
Thank you for your responses.  My apologies -- I wanted to contribute, but seem to have only wasted everyone's time.  My bad.

**Comment by JoeLoser** [comment]
> The first fix has also been applied in #2818.

Thanks - closing this PR then.

**Pull request closed without merging**
