### PR TITLE
[stdlib] Extending `FloatLiteral` comparison tests with special values

### PR DESCRIPTION
**Pull request by vguerra**
Testing `Comparable` dunder methods with special values: `nan`, `negative_zero`, `infinity`, `negative_infinity`

### CODE REVIEW

**Comment by vguerra** [comment]
hello @laszlokindrat , this PR addresses your suggestion in here https://github.com/modularml/mojo/pull/3216#discussion_r1679662562 regarding testing special values :).

**Comment by laszlokindrat** [comment]
Cool, thanks! Can you please also add cases for `nan`?

**Review by gryznar — COMMENTED** [review]
It may be cool to add comparisons for `inf` and `neg_inf` against some number, eg. `neg_zero` or/and the greatest/smallest possible

**Comment by vguerra** [comment]
> It may be cool to add comparisons for `inf` and `neg_inf` against some number, eg. `neg_zero` or/and the greatest/smallest possible

Thanks for the suggestion. Initially, I tried to write tests using greatest/smallest values possible and compare against `neg_inf` and `inf` but I did not manage to cast the values returned by [`max_finite`](https://docs.modular.com/mojo/stdlib/utils/numerics/max_finite)/[`min_finite`](https://docs.modular.com/mojo/stdlib/utils/numerics/min_finite) to `FloatLiteral`. 

For instance, this would not work:
```mojo
 var x = min_finite[DType.float16]().value
 assert_true(FloatLiteral.__lt__(neg_inf, x))
```

Do you know by chance how I could make this comparison work?

**Comment by gryznar** [comment]
Hmm, maybe someone from Modular would know? Laszlo / Joe / Abdul?

**Comment by vguerra** [comment]
> Cool, thanks! Can you please also add cases for `nan`?

added those in 53fe50a

**Comment by vguerra** [comment]
> It may be cool to add comparisons for `inf` and `neg_inf` against some number, eg. `neg_zero` or/and the greatest/smallest possible

What about merging this PR as is? I would rather tackle the above as a follow up. (cc: @laszlokindrat )

**Review by laszlokindrat — APPROVED** [review]
LGTM, thank you!

**Comment by laszlokindrat** [comment]
!sync

**Pull request closed without merging**
